### ISSUE TITLE
Auto-create notebook dir for users

### ISSUE THREAD

**Issue by bmcgough** [jupyterhub/sudospawner#19]
I have read and tried to follow https://github.com/jupyter/jupyterhub/issues/314 but I'm guessing I cannot subclass SudoSpawner in the same way.

Ultimately, I want to auto-create the notebook dir in the user's home directory. I understand why jupyterhub does not want to do this for everyone. We have a large user population, with only a smaller subset of jupyter users. Pre-creating for everyone doesn't make sense, the Server Error 500 is a bad experience, and even if it were easy to display an informative error message, it is still not a great user experience. So I'm left to hack it in. :(

Is there a similar way I can subclass SudoSpawner to add a directory creation routine run through sudo?

BTW, the reason we have set notebook dir to something other than the user's homedir is that we want users to be able to set permissions to share notebooks w/o accidentally compromising their homedir permissions. A jupyterhub sharing mechanism would also solve this issue.

**Comment by chris-x86-64** [comment]
This issue is about half a year old but since I came up with a solution while writing my own spawner module, I'll share it.

In your own Spawner subclass, you override the `_notebook_dir_validate()` so that it creates the missing directory, like this: https://github.com/chris-x86-64/rootlessspawner/commit/1107e82ba82890c96071c6c7f72cd8ec44aaf2e2#diff-2b6f4d7e188af73bd7937b36b7fd7114R46

P.S. My custom spawner module is called `rootlessspawner` because it never involves root, sudo nor any local system accounts-- instead it uses OpenLDAP.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
