### ISSUE TITLE
Configurable launch script vs security concerns

### ISSUE THREAD

**Issue by parente** [jupyterhub/sudospawner#25]
In the case where I want to keep my notebook server environment separate from my jupyterhub environment, it would be helpful to point to a script that activates the desired environment and then delegates the command line params to jupyterhub-singleuser. As it stands, I have to generate a script with that name, rename the actual juputerhub-singleuser script to something else, and then delegate to it.

I notice that the code comments say the jupyterhub-singleuser script is hardcoded "for security". Is there a known risk to respecting the Spawner.cmd traitlet (https://github.com/jupyterhub/jupyterhub/blob/2dd3463ea89e8be435fabe245e17f8e127252c3f/jupyterhub/spawner.py#L140) in the sudospawner? On first glance, it appears that only admin users with write access to the jupyterhub config would have to ability to set that executable command.

**Comment by parente** [comment]
Strawman for how I think this could get implemented:

1. Add a traitlet for the script name to execute to SudoSpawner so that it's configurable in the jupyterhub config (here https://github.com/jupyterhub/sudospawner/blob/master/sudospawner/spawner.py#L25)
2. Change the spawner so that it passes the script name to stdin of the mediator process in the JSON blob (https://github.com/jupyterhub/sudospawner/blob/master/sudospawner/spawner.py#L64)
3. Change mediator.py to pull the script to run out of the JSON blob (https://github.com/jupyterhub/sudospawner/blob/master/sudospawner/mediator.py#L134)

I'll send a PR with these changes if there's not a glaring security problem here that I'm missing (or a better way to do it).

**Comment by minrk** [comment]
Adding the single-user command to the mediator payload alongside argv would be the right way to implement it if that's what we should do.

I have trouble making a sane security argument when the goal is ultimately "run arbitrary code as the user". But the idea of sudospawner is that when you do the sudo config, you grant the Hub user permission to  perform a very limited set of actions on behalf of other users. By hardcoding the single-user command, the limits of the sudospawner actions are (relatively) clear:

1. launch `dirname(sudospawner)/jupyterhub-singleuser`
2. kill processes

By making the command configurable in jupyterhub_config.py, you are allowing the Hub user to specify its own permissions for what it is allowed to do on behalf of other users, rather than requiring (usually root) permission to modify installation directories.

So there's a qualitative difference:

- before: only root can change what the hub user can do on behalf of users
- after: the hub user gets to decide for itself what it can do on behalf of users

So the currently recommended config in `/etc/sudoers`:

```ini
# give the Hub user permission to run sudospawner on behalf of users
HUB_USER ALL=(JUPYTER_USERS) NOPASSWD:/usr/local/bin/sudospawner
```

becomes indistinguishable from

```ini
# give the Hub user permission to run sudospawner on behalf of users
HUB_USER ALL=(JUPYTER_USERS) NOPASSWD:ALL
```

granting the Hub user explicit permission to execute *any* command on behalf of other users, rather than just the mediator command, as the mediator command would become a trivial gateway to arbitrary other commands.

That doesn't mean it's the wrong thing to do, but it is a difference of some significance. Ultimately, the Hub can already run arbitrary code as other users, as it has enough information on its own to make authenticated websocket connections to the kernels (however tedious that would be).

**Comment by parente** [comment]
Thanks for that explanation. It helps me understand the intent of the current design.

> But the idea of sudospawner is that when you do the sudo config, you grant the Hub user permission to perform a very limited set of actions on behalf of other users.  ...
> 1. launch dirname(sudospawner)/jupyterhub-singleuser
> 2. kill processes

This setup works as long as the user account under which jupyterhub runs has read-only access to the installation of jupyterhub and its config file. If the hub user has read/write, then it can swap out the jupyterhub-singleuser script, change its own config, etc.

Following that line of thinking, is there a way we can grant root the ability to configure what script to launch and not allow the hub user to change that setting? My hacky approach at present is to overwrite the `jupyterhub-singleuser` with my custom copy as root and have it call the original. What about configuring the mediator script in another way that the jupyterhub process can't possibly change, even if it's gone rogue (e.g., a separate, root-owned config file?)

Maybe that's overkill and replacing the script as root like I'm already doing is the most secure, sensible option.

**Comment by minrk** [comment]
I have an idea that keeps the model roughly the same, but gives you a more convenient/official way to override the launch behavior. PR incoming...

**Comment by minrk** [comment]
#26 is my idea, let me know if it seems satisfactory to you.
